# Registro de usuario en el sistema
guikifix_api_register_user:
  path: /register
  defaults: { _controller: GuikifixApiBundle:User\Security:register }
  methods: POST

# Petici贸n de login de un usuario asincronamente.
guikifix_api_login:
  path:   /login
  defaults: { _controller: GuikifixApiBundle:User\Security:apilogin, config : 'main'}
  methods: POST

# Petici贸n de logout de un usuario asincronamente.
guikifix_post_api_logout:
  path:   /post/logout
  defaults: { _controller: GuikifixApiBundle:User\Security:postLogout}

# Petici贸n de para actualizacion del password de un usuario asincronamente.
guikifix_api_reset_password:
  path:   /update/password
  defaults: { _controller: GuikifixApiBundle:User\Security:updatePassword}
  methods: POST

# Petici贸n de para saber si el usuario esta logeado.
guikifix_api_is_logged:
  path:   /is/logged
  defaults: { _controller: GuikifixApiBundle:User\Security:isLogged}
  methods: POST